### ISSUE TITLE
notifications are just black text and targeting is a little buggy

### ISSUE THREAD

**Issue by SepticLime** [devin-monro/FiveM-QBCore-Money-Wash#1]
love the resource great job ! Only issues I seem to have are notifications which are just black text not certain if this was intended but if its changeable that would be amazing. Also targeting the washing machines works it can just be very touchy. If this could be improved this would become a A+ resource and much better than qb-traphouse in my option. great job once again.

**Comment by darktrovx** [comment]
Fixed with this latest update.
The third eye will always be "slightly" delayed due to how the Callback system works.
They require a Wait in order to store the data correctly before I can return the true/false for displaying.
